let actionTypes = {
  ADD_CHAT: 'ADD_CHAT',
  ADD_CHAT_INBOUND: 'ADD_CHAT_INBOUND',
  ADD_CHATS: 'ADD_CHATS',
  CHANGE_CHAT: 'CHANGE_CHAT',
  CHANGE_CHAT_INBOUND: 'CHANGE_CHAT_INBOUND',
  LEAVE_CHAT: 'LEAVE_CHAT',
  SELECT_CHAT: 'SELECT_CHAT',

  ADD_MESSAGE: 'ADD_MESSAGE',
  ADD_MESSAGE_INBOUND: 'ADD_MESSAGE_INBOUND',
  ADD_MESSAGES: 'ADD_MESSAGES',
  CONFIRM_MESSAGE: 'CONFIRM_MESSAGE',
  CHECK_SIGNATURE: 'CHECK_SIGNATURE',
  RESPONSE_CHECK_SIGNATURE: 'RESPONSE_CHECK_SIGNATURE',

  SET_USERNAME: 'SET_USERNAME',
  SET_CONNECTION: 'SET_CONNECTION',

  ADD_PEERS: 'ADD_PEERS',

  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',

  SOCKET_CLOSED: 'SOCKET_CLOSED',
  SOCKET_OPEN: 'SOCKET_OPEN'
};

export default Object.freeze(Object.assign({}, actionTypes));
